using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CricketLinking
{
    class Global
    {
        public static string[] multiBATWords = { "unbeaten", "magnificent", "cameo", "blitz", "knock", "top-scored", "stay", "strokeplay", "form", "explosive", "punches", "score", "bat", "craftsman", "power-hitting", "shots", "ton", "shattered", "covers", "whipping", "hammering", "opener", "stroked", "style", "momentum", "match-winning", "graceful", "drives", "run-scorer", "clubbed", "muscled", "slapped", "flick", "audacious", "smashing", "flexed", "stride", "exploding", "scintillating", "free-stroking", "well-paced", "chips", "big-hitting" };
        public static string[] multiBOWLWords = { "figures", "economy", "yorkers", "tidy", "conceding", "cutters", "spells", "fast", "expensive", "bowler", "brilliant", "spell", "effective", "bowlers", "five-for", "offbreaks", "economical", "trajectory", "mesmeric", "cunning", "fabulous", "wicketless", "disciplined" };
        public static string[] multiBATBOWLWords= {};
        public static string[] multiWICKETSWords = { "wickets", "dismissed", "removed", "lost", "five-for", "hat-trick", "picking", "shipped", "openers", "quick", "collapse", "five-wicket", "tail", "fell", "losing", "torment", "touches", "terrific", "game", "trapped", "space", "scalps", "lose", "claiming", "haul", "remaining", "claimed", "vital", "picked", "reverse-swing", "devastating", "stunned", "fall", "derail", "removing", "dismiss", "quicks", "four-wicket", "dismissals", "clinical", "three-for", "ripping", "misery", "swift", "crucial", "snaring", "lbw", "victims", "demolished", "storming", "line-up", "perished", "tame", "rein", "dismissal", "humiliation", "tight", "collapse", "wicket-taking", "rip", "seven-wicket", "doom" };
        public static string[] multiPARTNERSHIPWords = { "stand", "partnership", "highest", "pair", "together", "record", "company", "opening", "laid", "combination", "adding", "strong", "third-wicket", "between", "put", "fourth-wicket", "platform", "steadied", "decisive", "broken", "partnerships", "added", "second-wicket", "seven-wicket", "partner", "pairs", "rebuild", "slowly", "ninth-wicket", "pairing", "partnered", "ending" };
        public static string[] multiEXTRASWords = { "extras", "whopping", "no-balls", "wides", "glut", "totted", "foot-faults", "blockhole", "full-tosses", "waist-high", "conceded" };
        public static string[] multiSIXWords = { "long-on", "stands", "monstrous", "biggest", "massive", "six", "clean", "one-handed", "cleared", "sixes", "huge", "powerful", "blow", "launch", "high", "swat", "smite", "walloped", "flat", "smash", "flick", "swinging", "swing", "pitched", "crashed", "handsome", "stroke", "smashed", "shot", "six", "sky", "loft", "blow", "monster", "boards", "roaring", "force", "impact", "significant", "smeared", "crushes", "carnage", "stunning", "behemoth", "fired", "swiped", "violent", "murderous", "fence", "big-bang", "hammered" };
        public static string[] multiFOURWords = { "forward", "square-leg", "pushed", "outside", "fine-leg", "four", "flicked", "fortuitous", "crunched", "steered", "upar", "boundaries", "scoop", "fours", "cut", "boundary", "covers", "locating", "edge", "nerveless", "drives", "skywards", "flicking", "power", "spot", "pounded", "edged", "swept", "slog", "flurry", "heist", "boundary", "hammered", "hitting", "whip" };
        public static string[] multiOVERSWords = { "penultimate", "maiden" };
        public static string[] multiOTHERSWords = { "knee", "right", "half-centuries", "required", "needs", "pad", "lobbed", "field", "injury", "feet", "spectators", "crease", "hands", "injuring", "strain", "thigh" };
        public static string[] multiPOWERPLAYWords = { "powerplay", "mandatory", "five-over", "batting-powerplay", "restrictions" };
        public static string[] multiREFERRAL_DROPPEDWords = { "chances", "catches", "referrals", "stumpings", "missed", "caught", "lives", "convinced", "decisions", "reviews", "dropped", "twice", "calls", "run-out", "drops", "reprieves", "disastrous", "dropping", "begging", "glovework", "fluff", "shout", "prompted", "surviving", "overturned", "attempts", "failed", "caught-and-bowled", "stumping", "opportunities", "survived", "spill", "beaten", "mistimed" };
        public static string[] multipleClasses = { "BAT","BOWL","BATBOWL","WICKETS","PARTNERSHIP","EXTRAS","FOUR", "SIX", "OVERS", "OTHERS", "POWERPLAY", "REFERRAL-DROPPED"};

        public static string[] BALLwords = { "fifty", "hundred", "century", "reached", "100", "half-century", "fastest", "centuries", "aggressive", "raced", "half-century,", "50-ball", "balls", "ton" };
        public static string[] DROPPEDwords = { "dropped", "stopped", "shelled", "sitter", "dropping", "reprieve", "spilled", "catches", "hold", "ropes", "grass", "hands", "straightforward", "fly", "realised", "seen", "flew", "slip", "fingers", "skier", "unfortunately", "cleanly", "collect", "whisker", "mishit", "lazily", "bungled", "flinch", "sadly", "survived", "chances", "flailed", "life", "fumble", "attempt", "unsuccessful", "awful", "pouch", "display", "shoddy", "spilling", "splattered", "narrowly", "direct", "chance", "failing", "shock", "latch", "mishaps", "converged", "mistake", "messed", "error", "follow-through,", "gaffe", "drop", "chance", "edged", "survived", "missing", "fumbled" };
        public static string[] FOURwords = { "upar", "square-leg", "steered", "four", "scoop", "finesse", "boundaries", "hammered", "timing", "wrists", "step", "steps", "thump", "cream", "square", "flicked", "whirling", "slap", "classy", "flowingly", "muscular", "elegance", "cover-drive", "masterpiece", "larruped", "whiplashed", "whip", "timed", "slammed" };
        public static string[] LASTBALLwords = { "victory", "defeat", "win", "tie", "result", "margin", "winning", "humiliating", "triumph", "won", "upset", "thrilling", "tied", "thrashing", "beating", "wickets", "romped", "loss", "wallop", "crushing", "total", "thumping", "imploded", "incredible", "coasted", "chasing", "amassed", "thrashed", "heart-stopping", "resounding", "history", "run-chase", "historic", "achievement", "delirium", "demoralising", "demolition", "pandemonium", "belted", "match-winning", "target", "finishing", "collapsing", "enormous", "defeated", "emphatic", "snatched", "dismal", "margins", "defeat" };
        public static string[] SIXwords = { "stands", "one-handed", "six", "smash", "cleared", "swat", "monstrous", "blow", "walloped", "launch", "powerful" };
        public static string[] OUTwords = { "stump", "dismissal", "dismissed", "run-out", "stumping", "stumped", "beaten", "departed", "caught", "nipped", "victim" };//"played", "found", "ended", "give", "fall", "inches", "slog", "attempted", , "picked", "trapping", "wild", "slip", "lose", "edging", "skidding", "flighted", "rid", "dismiss", "departure", "holed", "top-edged", "outswinger", "remove", "removed", "perished", "crucial", "ending", "clip", "charged", "yorker", "breakthrough", "inswinger", "turn", "removal", "chipped", "offspinner", "ripped", "duck", "shout", "trapped", "pads", "straightened", "inswinging", "nicked", "wicket", "lazy", "keeper", "dived", "stumps", "lbw", "outstretched", "fell", "catch", "attempting", "defences", "slashed", "umpires", "swing", "plucked", "swung", "undone", "tempted", "popped", "dismissing", "miss", "bails", "snared", "scalp", "caught-and-bowled", "run-outs", "throw", "mistimed", "snare", "edge", "googly", "incutter", "falling", "gloves", "rattle"
        public static string[] REFERRALwords = { "evidence", "review", "challenged", "incident", "favour", "verdict", "controversial", "replays", "screen", "lbw", "referral", "deemed", "overturned", "convinced", "reprieved" };
        public static string[] OTHERwords = { "knee", "no-ball", "wides", "strain", "overstepped", "clutching", "thigh", "injury" };
        public static string [] singleClasses = {"BALL","DROPPED","FOUR","LASTBALL","SIX","OTHERS","OUT","REFERRAL"};
        public static string baseDir = @"D:\research\current\2015_Cricket_Linking\data\";
        public static int numMatches = 30;
        public static string[] powerPlayWords = { "powerplay", "mandatory", "five-over", "batting-powerplay", "restrictions" };
        public static string[] derivedEntities = { "bat", "bowl", "powerplay", "extras", "yorkers", "reverse", "wickets", "partnership", "free-hits", "dotballs", "dot", "singles", "wides"};
        public static int numInningsPerMatch = 2;
        public static string[] discriminativeSingleMentionWords = {"hundred","ton","century", "half-century", "delivery", "catch", "defeat", "edge", "drive", "umpire", "stump", "lbw", "dismissal", "victory", "win", "line", "slip", "pad", "outside", "right", "chance", "stumps", "towards", "being", "replays", "Prior", "edged", "fifty", "yorker", "run-out", "moment", "hands", "forward", "run", "seemed", "referral", "onto", "make", "low", "asked", "given", "won", "wicketkeeper", "throw", "review", "pitched", "held", "ground", "fielders", "backward", "shot", "leg", "tie", "thought", "slower", "high", "couldn't", "boundary", "appeal", "run-out" };
        public static string[] discriminativeMultipleMentionWords = { "hat-trick", "partnership", "boundaries", "fours", "pair", "singles", "unbeaten", "taking", "Powerplay", "twice", "figures", "batting", "stand", "sixes", "ones", "conceded", "record", "wickets", "overs", "mandatory", "haul", "together", "successive", "half-centuries", "dot", "twos", "magnificent", "extras", "economy", "run-outs", "chances" };
        public static string[] singularEventWords ={"six", "four", "out", "review", "boundary", "referral", "wide", "bye", "leg bye", "caught", "dropped", "chance", "no-ball"};
        public static string[] multipleEventWords = { "overs", "sixes", "fours", "boundaries", "wickets", "reviews", "wides", "extras", "chances" };
        //List of batting shots taken from http://en.wikipedia.org/wiki/Batting_(cricket)
        public static string[] shots = { "cut", "square cut", "late cut", "square drive", "cover drive", "off drive", "straight drive", "on drive", "pull", "hook", "leg glance", "block", "forward defensive", "backward defensive", "off glance", "lofted drive", "sweep", "paddle sweep", "reverse sweep", "slog", "slog sweep", "upper cut", "switch hit", "scoop", "ramp", "paddle scoop", "marillier", "dilscoop"};
        //Types of balls taken from http://en.wikipedia.org/wiki/Bowling_(cricket)
        public static string[] balls = { "bouncer", "inswinger", "leg cutter", "off cutter", "outswinger", "reverse swing", "slow", "slower", "yorker", "arm ball", "doosra", "teesra", "fliper", "googly", "carrom", "leg spin", "off spin", "slider", "topspinner", "spin", "fast", "full toss", "beamer", "pace", "seam", "swing", "legbreak", "offbreak", "short" };
        //Fielding positions taken from http://en.wikipedia.org/wiki/File:Cricketfieldingpositions.jpg
        public static string[] fieldPos = { "long stop", "third man", "deep backward point", "deep point", "deep cover", "deep extra cover", "long off", "straight hit", "long on", "cow corner", "deep midwicket", "deep square leg", "long leg", "deep fine leg", "fine leg", "short fine leg", "backward square leg", "square leg", "midwicket", "mid on", "mid off", "extra cover", "cover", "point", "backward point", "short third man", "gully", "fly slip", "leg slip", "first slip", "second slip", "third slip", "fourth slip", "leg gully", "short leg", "silly mid on", "silly mid off", "silly point", "outside off", "outside on"};
        public static string[] wicketWords = { "bowled", "struck", "dismissal", "dismissed", "stumped", "bowled", "knocked", "lbw", "snicking", "deceived", "taking the off stump", "caught", "stump knocked", "stumped", "duck", "dispatched", "finding the edge", "removed", "caught", "gloved", "hitting wicket", "breakthrough", "fell", "caught", "mistake", "given", " taken", "glided", "straight to", "run out", "run-out", "caught out", "caught-out", "bowled out", "bowled-out", "stumped out", "stump out", "stump-out", "stumped-out" };
        public static string[] fourWords = { "boundary", "boundaries", "fours", "four", "covers", "meaty blows", "thrashing", " big-hitting", "strike", "lifting", "maximum", "shot", "threading", "thumping" };
        public static string[] shotKeywords = { "scored", "hit", "smash" };
        public static string[] sixWords ={"six","sixes","meaty blows","aerial","in the stands","big hit"};
        public static string[] extrasWords = { "wide", "wides", "no", "bye", "byes", "leg-byes", "leg-bye", "no-ball" };
        public static string[] partnershipWords = { "stand", "partnership", "highest", "pair", "together", "record", "company", "opening", "laid", "combination", "adding", "strong", "third-wicket", "between", "put", "fourth-wicket", "platform", "steadied", "decisive", "broken", "partnerships", "added", "second-wicket", "seven-wicket", "partner", "pairs", "rebuild", "slowly", "ninth-wicket", "pairing", "partnered", "ending", "run-stand", "wicket-stand" };
        public static string[] units = { "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen" };
        public static string[] tens = {"", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"};
        public static string[] scales = { "hundred", "thousand", "million", "billion", "trillion" };
        public static string[] countries={"australia","england","west indies","india","pakistan","bangladesh","sri lanka","new zealand","south africa","ireland","zimbabwe","kenya","netherlands","canada"};
        public static Dictionary<string, int> word2Num = new Dictionary<string, int>() { { "century", 100 }, { "half century", 50 }, { "half-century", 50 }, { "fifty", 50 }, { "double century", 200 }, { "double-century", 200 }};
        public static string[] overs = {
			"(.)*\\d+th over(.)*",
			"(.)*\\d+rd over(.*)",
			".*(first|second|third|fourth|fifth|sixth|seventh|eighth|nineth|tenth) over.*",
			".*(one|two|three|four|five|six|seven|eight|nine|ten) over.*" };
        public static string[] runs = { ".*\\d+ runs.*", ".*\\d+ for.*", ".*\\d+ from.*", ".*scored \\d+.*" };
        public static string[] balls2 = {
			".*\\d+ ball.*",
			".*(first|second|third|fourth|fifth|sixth|seventh|eighth|nineth|tenth) ball(.)*",
			".*(one|two|three|four|five|six|seven|eight|nine|ten) ball.*" };
        public static string[] cricketVocab = { "leg cutter", "innings", "middle of the bat", "strike-rate", "sitter", "put down", "dropped", "down the ground", "hawk eye", "roll", "switch hit", "beamer", "appeal", "all out", "backfoot", "cross bat", "in-cutter", "long-off", "doosra", "leg-bye", "off-cutter", "wide", "batter", "off side", "corridor of uncertainty", "inside edge", "chinaman", "off cutter", "square leg", "slog sweep", "mid off", "chuck", "six", "captain", "in cutter", "deep leg", "leg side", "leave", "hawk-eye", "caught", "economy-rate", "chin-music", "outside edge", "reverse-swing", "leading-edge", "short leg", "caught and bowled", "plumb", "net run rate", "run-rate", "slice", "defend", "closing-the-face", "wrist spin", "bowled", "full length", "hit-the-deck", "lbw", "drop", "arm-ball", "bounce", "boundary", "switch-hit", "leg-side", "away swing", "back foot", "partnership", "long-on", "bat-pad", "mid on", "sweep", "bowl-out", "full-toss", "hat trick", "no-ball", "ring field", "off-side", "on side", "half-volley", "paddle", "carromball", "silly point", "carrom ball", "corridor-of-uncertainty", "on the up", "retire", "half century", "side on", "long on", "powerplay", "away-swing", "ton", "economy rate", "four", "closing the face", "strike rate", "wicket", "hit the deck", "five", "short covers", "back-foot", "charge", "reverse sweep", "third-man", "deep-leg", "bowl out", "cross-bat", "defends", "hat-trick", "out", "hit wicket", "asking-rate", "dead ball", "rock", "bouncer", "crease", "drive", "leg break", "off-break", "fifty", "cameo", "extra", "net runrate", "asking rate", "fine leg", "free hit", "extras", "googly", "off break", "good length", "covers", "bat pad", "run rate", "off the mark", "long off", "delivery", "third man", "square-leg", "net-runrate", "behind square", "pair", "line", "front foot", "chucker", "swept away", "leg glance", "leg bye", "leg-cutter", "length", "spin", "reverse-sweep", "ball", "slip", "leading edge", "arm ball", "loosener", "on-side", "flight", "dilscoop", "point", "leg-glance", "midwicket", "cut", "square", "fielder", "meat of the bat", "leg-before wicket", "pace", "zooter", "single", "runrate", "guly", "good-length", "inside-edge", "footwork", "middle", "anchor", "clean-bowled", "tailender", "short cover", "no ball", "allout", "centurion", "three", "duck", "outswing", "swing", "punch", "strikerate", "flipper", "inside-out shot", "backward point", "chin music", "fielding", "leg-break", "pitch", "reverse swing", "stumps", "one", "carrom-ball", "bowlout", "slog", "clean bowled", "seam", "nightwatchman", "full toss", "slog-sweep", "extra cover", "maiden", "half volley", "rip", "leg stump", "inside out", "century", "yorker", "bye", "two", "dead-ball", "runner" };
        public static string[] reviewWords = { "review","referral","third_umpire","referred"};
    }
}
